export const NOTIFICATION_PRIORITIES = ["LOW", "MEDIUM", "HIGH"]
export const NOTIFICATION_STATUSES = ["UNREAD", "READ", "ARCHIVED"]

export const NOTIFICATION_TYPES = {
  ACTIVITY_REMINDER: "ACTIVITY_REMINDER",
  FLIGHT_DEPARTURE: "FLIGHT_DEPARTURE",
  FLIGHT_CHECKIN: "FLIGHT_CHECKIN",
  FLIGHT_GATE_CLOSE: "FLIGHT_GATE_CLOSE",
  FLIGHT_BOARDING: "FLIGHT_BOARDING",
  HOTEL_CHECKIN: "HOTEL_CHECKIN",
  HOTEL_CHECKOUT: "HOTEL_CHECKOUT",
  WEATHER_ALERT: "WEATHER_ALERT",
  BUDGET_WARNING: "BUDGET_WARNING",
  COLLAB_JOIN: "COLLAB_JOIN",
  COLLAB_EDIT: "COLLAB_EDIT",
  COLLAB_COMMENT: "COLLAB_COMMENT",
  COLLAB_REVIEW: "COLLAB_REVIEW",
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  BOOKING_UPDATED: "BOOKING_UPDATED",
  AI_REMINDER: "AI_REMINDER",
  TRIP_CREATED: "TRIP_CREATED",
  TRIP_UPDATED: "TRIP_UPDATED",
  CALENDAR_SYNCED: "CALENDAR_SYNCED",
  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
  DOCUMENT_EXPIRING: "DOCUMENT_EXPIRING",
  PACKING_REMINDER: "PACKING_REMINDER",
  TRAVEL_RISK_ALERT: "TRAVEL_RISK_ALERT",
  SCHEDULE_CONFLICT: "SCHEDULE_CONFLICT",
  FLIGHT_DELAY: "FLIGHT_DELAY",
  FLIGHT_GATE_CHANGE: "FLIGHT_GATE_CHANGE",
  FLIGHT_CANCELLED: "FLIGHT_CANCELLED",
  FLIGHT_BAGGAGE: "FLIGHT_BAGGAGE",
  FLIGHT_STATUS_UPDATE: "FLIGHT_STATUS_UPDATE",
  BUDGET_OPTIMIZATION: "BUDGET_OPTIMIZATION",
  BUDGET_SAVINGS_AVAILABLE: "BUDGET_SAVINGS_AVAILABLE",
  TRAVEL_MILESTONE: "TRAVEL_MILESTONE",
}

/** Filter categories for UI */
export const NOTIFICATION_CATEGORIES = {
  ALL: "all",
  UNREAD: "unread",
  TRAVEL: "travel",
  BUDGET: "budget",
  WEATHER: "weather",
  BOOKINGS: "bookings",
  AI: "ai",
  COLLABORATION: "collaboration",
}

const TRAVEL_TYPES = new Set([
  NOTIFICATION_TYPES.ACTIVITY_REMINDER,
  NOTIFICATION_TYPES.FLIGHT_DEPARTURE,
  NOTIFICATION_TYPES.FLIGHT_CHECKIN,
  NOTIFICATION_TYPES.FLIGHT_GATE_CLOSE,
  NOTIFICATION_TYPES.FLIGHT_BOARDING,
  NOTIFICATION_TYPES.FLIGHT_DELAY,
  NOTIFICATION_TYPES.FLIGHT_GATE_CHANGE,
  NOTIFICATION_TYPES.FLIGHT_CANCELLED,
  NOTIFICATION_TYPES.FLIGHT_BAGGAGE,
  NOTIFICATION_TYPES.FLIGHT_STATUS_UPDATE,
  NOTIFICATION_TYPES.HOTEL_CHECKIN,
  NOTIFICATION_TYPES.HOTEL_CHECKOUT,
  NOTIFICATION_TYPES.TRIP_CREATED,
  NOTIFICATION_TYPES.TRIP_UPDATED,
])

const BUDGET_TYPES = new Set([
  NOTIFICATION_TYPES.BUDGET_WARNING,
  NOTIFICATION_TYPES.BUDGET_OPTIMIZATION,
  NOTIFICATION_TYPES.BUDGET_SAVINGS_AVAILABLE,
])
const TRAVEL_ANALYTICS_TYPES = new Set([NOTIFICATION_TYPES.TRAVEL_MILESTONE])
const WEATHER_TYPES = new Set([NOTIFICATION_TYPES.WEATHER_ALERT])
const BOOKING_TYPES = new Set([
  NOTIFICATION_TYPES.BOOKING_CONFIRMED,
  NOTIFICATION_TYPES.BOOKING_CANCELLED,
  NOTIFICATION_TYPES.BOOKING_UPDATED,
])
const DOCUMENT_TYPES = new Set([
  NOTIFICATION_TYPES.DOCUMENT_UPLOADED,
  NOTIFICATION_TYPES.DOCUMENT_EXPIRING,
  NOTIFICATION_TYPES.PACKING_REMINDER,
])
const CALENDAR_TYPES = new Set([NOTIFICATION_TYPES.CALENDAR_SYNCED])
const AI_TYPES = new Set([
  NOTIFICATION_TYPES.AI_REMINDER,
  NOTIFICATION_TYPES.TRAVEL_RISK_ALERT,
  NOTIFICATION_TYPES.SCHEDULE_CONFLICT,
])
const COLLAB_TYPES = new Set([
  NOTIFICATION_TYPES.COLLAB_JOIN,
  NOTIFICATION_TYPES.COLLAB_EDIT,
  NOTIFICATION_TYPES.COLLAB_COMMENT,
  NOTIFICATION_TYPES.COLLAB_REVIEW,
])

export function categoryForType(type) {
  if (TRAVEL_TYPES.has(type)) return NOTIFICATION_CATEGORIES.TRAVEL
  if (BUDGET_TYPES.has(type)) return NOTIFICATION_CATEGORIES.BUDGET
  if (TRAVEL_ANALYTICS_TYPES.has(type)) return NOTIFICATION_CATEGORIES.TRAVEL
  if (WEATHER_TYPES.has(type)) return NOTIFICATION_CATEGORIES.WEATHER
  if (BOOKING_TYPES.has(type)) return NOTIFICATION_CATEGORIES.BOOKINGS
  if (DOCUMENT_TYPES.has(type)) return NOTIFICATION_CATEGORIES.TRAVEL
  if (CALENDAR_TYPES.has(type)) return NOTIFICATION_CATEGORIES.BOOKINGS
  if (AI_TYPES.has(type)) return NOTIFICATION_CATEGORIES.AI
  if (COLLAB_TYPES.has(type)) return NOTIFICATION_CATEGORIES.COLLABORATION
  return NOTIFICATION_CATEGORIES.ALL
}

export function typesForCategory(category) {
  switch (category) {
    case NOTIFICATION_CATEGORIES.TRAVEL:
      return [...TRAVEL_TYPES, ...DOCUMENT_TYPES]
    case NOTIFICATION_CATEGORIES.BUDGET:
      return [...BUDGET_TYPES]
    case NOTIFICATION_CATEGORIES.WEATHER:
      return [...WEATHER_TYPES]
    case NOTIFICATION_CATEGORIES.BOOKINGS:
      return [...BOOKING_TYPES, ...CALENDAR_TYPES]
    case NOTIFICATION_CATEGORIES.AI:
      return [...AI_TYPES]
    case NOTIFICATION_CATEGORIES.COLLABORATION:
      return [...COLLAB_TYPES]
    default:
      return null
  }
}

export const EMAIL_ELIGIBLE_TYPES = new Set([
  NOTIFICATION_TYPES.FLIGHT_DEPARTURE,
  NOTIFICATION_TYPES.FLIGHT_CHECKIN,
  NOTIFICATION_TYPES.FLIGHT_GATE_CLOSE,
  NOTIFICATION_TYPES.FLIGHT_BOARDING,
  NOTIFICATION_TYPES.HOTEL_CHECKIN,
  NOTIFICATION_TYPES.HOTEL_CHECKOUT,
  NOTIFICATION_TYPES.WEATHER_ALERT,
  NOTIFICATION_TYPES.BUDGET_WARNING,
])
